stages:
  - lint
  - test


backend-lint:
  stage: lint
  image: python:3.12-slim
  before_script:
    - pip install --quiet autoflake isort black
  script:
    - autoflake --check --remove-all-unused-imports -r backend/app/
    - isort --check backend/app/
    - black --check backend/app/

backend-test:
  stage: test
  image: python:3.12-slim
  before_script:
    - cd backend
    - pip install --quiet -e ".[dev]"
  script:
    - coverage run -m --branch pytest tests/ -v
    - coverage report
    - coverage html
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    paths:
      - backend/htmlcov/
    expire_in: 1 day


frontend-lint:
  stage: lint
  image: node:20-slim
  before_script:
    - cd frontend
    - npm ci --quiet
  script:
    - npm run lint

frontend-test:
  stage: test
  image: node:20-slim
  before_script:
    - cd frontend
    - npm ci --quiet
  script:
    - npm test
