[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"]

[project]
name = "onto-curate-backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]>=0.30.0",
    "sqlalchemy[asyncio]",
    "asyncpg",
    "alembic",
    "httpx",
    "pyoxigraph",
    "celery[redis]",
    "redis",
    "python-multipart",
    "pydantic-settings",
    "ontogpt",
    "rapidfuzz",
    "rdflib",
    "pyyaml",
    "scikit-learn",
    "pymupdf4llm",
    "pronto>=2.7.3",
    "google-auth",
    "PyJWT",
    "pwdlib[bcrypt]",
    "argon2-cffi",
    "pydantic[email]"
]

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "pytest",
    "pytest-asyncio",
    "httpx",
    "pydantic_settings",
    "python-multipart",
    "python-dotenv",
    "pyoxigraph",
    "coverage",
]

[tool.isort]
known_first_party = ["config", "api", "app"]
profile = "black"

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["app"]
