# Entity alignment configuration.
settings:
  # Minimum similarity score for proposed owl:sameAs alignment 
  default_threshold: 0.8

  # Metric weights (must sum to 1.0)
  default_weights:
    syntactic: 0.6
    semantic: 0.3
    structural: 0.1

  # Default fields used for syntactic similarity 
  default_comparison_predicates:
    - name

  # Default fields used for semantic similarity
  default_semantic_text_predicates:
    - name

  # Whether for every field initials should be considered during matching (i.e. single character matches first character of full token)
  default_expand_initials: false

  # Unique Keys
  unique_keys:
    - identifier
    - doi
    - issn
    - eissn

entity_types:
  Person:
    threshold: 0.75
    weights:
      syntactic: 0.7
      semantic: 0.0
      structural: 0.3
    comparison_predicates:
      - family_name
      - name
      - email
    semantic_text_predicates:
      - name
      - given_name
      - family_name
      - email
    expand_initials: true

  Organization:
    threshold: 0.82
    weights:
      syntactic: 0.5
      semantic: 0.4
      structural: 0.1
    comparison_predicates:
      - org_name
      - location
    semantic_text_predicates:
      - org_name
      - location

  Conference:
    threshold: 0.81
    weights:
      syntactic: 0.2
      semantic: 0.75
      structural: 0.05
    comparison_predicates:
      - conf_name
      - location
    semantic_text_predicates:
      - conf_name
      - location
    expand_initials: true

  Workshop:
    threshold: 0.85
    weights:
      syntactic: 0.45
      semantic: 0.45
      structural: 0.1
    comparison_predicates:
      - workshop_name
      - location
    semantic_text_predicates:
      - workshop_name
      - location

  Proceedings:
    threshold: 0.88
    weights:
      syntactic: 0.6
      semantic: 0.3
      structural: 0.1
    comparison_predicates:
      - title
      - volume
      - publication_year
    semantic_text_predicates:
      - title

  Journal:
    threshold: 0.9
    weights:
      syntactic: 0.6
      semantic: 0.4
      structural: 0.0
    comparison_predicates:
      - title
      - issn
      - eissn
    semantic_text_predicates:
      - title

  Series:
    threshold: 0.9
    weights:
      syntactic: 0.6
      semantic: 0.4
      structural: 0.0
    comparison_predicates:
      - series_name
      - issn
    semantic_text_predicates:
      - series_name
